version: "3"
services:
    web:
        build: ./Admin/Admin
        depends_on:
            - db
        labels:
            - "SERVICE_NAME=QuestionBank"
            - "SERVICE_TAGS=questionbanktag"
        expose:
            - "80"
        volumes:
            - "/machine_config:/app/machine_config"
        env_file:
            - .env
    db:
        image: "mongo:latest"
        