version: "3"
services:
    web:
        build: ./Admin
        expose:
            - "80"
        depends_on:
            - db
        labels:
            - "SERVICE_NAME=QuestionBank"
            - "SERVICE_TAGS=QuestionBankTag"
        volumes:
            - "/machine_config:/app/machine_config"
    db:
        image: "mongo:latest"
        